name: osedev

layers:
  base:
    from: damoti/base:latest
    context:
      - requirements/base.pip
    build:
      - pip3 install -r requirements/base.pip
  app:
    context:
      - .
    build:
      - cd /app/ose/dart && pub get && pub build
      - cd /app/ose/static && npm install && gulp
      - cd /app
      - pip3 install --src=/src -r requirements/app.pip
      - export DJANGO_SETTINGS_MODULE=ose.settings.common
      - python3 manage.py collectstatic --noinput
    prepare: fab prepare
    start: fab uwsgi
    wait-for: db:5432
  test:
    build:
      - pip3 install -r requirements/test.pip
    start: fab test
    wait-for: db:5432

build:
  branches:
    - master
